### ISSUE TITLE
Service URL for InterMine

### ISSUE THREAD

**Issue by Meganmli** [intermine/pombemine#72]
If it exists, what is the PombeMine service URL when trying to run this below in python v3?
```
from intermine.webservice import Service
service = Service({service_url})
```

**Comment by gmicklem** [comment]
Hi Megan,

I'm not sure of the context but you can find example service urls relating to the
individual template queries (a) and by generating code from queries (b)


(a) Visit https://www.pombase.org/im/pombemine/templates

For instance for the first 10 rows of the template:
    Disease (MONDO) -> Genes

the service url is:

https://pombemine.rahtiapp.fi/pombemine/service/template/results?name=MONDO_disease_to_genes&constraint1=Gene.diseases.mondoTerm.parents.name&op1=eq&value1=Cornelia+de+Lange+syndrome&format=tab&size=10

and likewise for the template:
    All protein coding gene(s) 

it is

https://pombemine.rahtiapp.fi/pombemine/service/template/results?name=protein_coding_genes&constraint1=Gene.description&op1=ne&value1=retrotransposable+element%2Ftransposon+Tf2-type&constraint2=Gene.description&op2=ne&value2=dubious&format=tab&size=10



(b) if you run a query (e.g. one of the template above), you can also generate code from
the query results page using the button towards to the top right of the results table
(default value of the drop-down is Python).

However instead of

   https://pombemine.rahtiapp.fi/pombemine/service

this seems to be giving the service url as

   http://localhost:8080/pombemine/service

which doesn't seem right.

I hope this helps.

Best wishes,

Gos

**Comment by Meganmli** [comment]
Hello! Sorry for not providing more context. I appreciate the detailed response!

**https://pombemine.rahtiapp.fi/pombemine/service** was exactly what I needed as **http://localhost:8080/pombemine/service** errored out when I tried to connect using this URL.

Thank you!

**Comment by kimrutherford** [comment]
Hi Megan.

I've also just added this as a more user friendly alias for the service URL: https://www.pombase.org/pombemine/service/
and I'll add that to the PomBase FAQ.

Thanks for helping out @gmicklem
